blank_issues_enabled: false
contact_links:
    - name: Request a feature
      url: https://github.com/m1guelpf/laravel-apple-login/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/m1guelpf/laravel-apple-login/issues/new
      about: Report a reproducable bug
